name: Build APk baru

on:
  workflow_dispatch: # Sah! Cuma jalan kalau diklik manual dari web GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: Cek atau Buat debug.keystore
      run: |
        KEYSTORE_PATH="${{ github.workspace }}/debug.keystore"
        if [ -f "$KEYSTORE_PATH" ]; then
          echo "debug.keystore terdeteksi, menggunakan file yang ada."
        else
          echo "debug.keystore tidak ditemukan, membuat baru..."
          keytool -genkeypair -alias androiddebugkey -keypass android -keystore "$KEYSTORE_PATH" -storepass android -dname "CN=Android Debug,O=Android,C=US" -keyalg RSA -keysize 2048 -validity 365
        fi

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.0
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '13114758'
        packages: 'platforms;android-36.1 build-tools;36.1.0 platform-tools'

    - name: Install NDK & Suntik Konfigurasi Gradle
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;28.2.13676358"
        echo "NDK_HOME=$ANDROID_HOME/ndk/28.2.13676358" >> $GITHUB_ENV
        sed -i '10i\        \n    ndkVersion = "28.2.13676358"' "${{ github.workspace }}/app/build.gradle.kts"
        sed -i '/android {/a \    splits { abi { isEnable = true; reset(); include("armeabi-v7a", "arm64-v8a"); isUniversalApk = false } }' "${{ github.workspace }}/app/build.gradle.kts"

    - name: Download AAR & Assets
      run: |
        mkdir -p app/libs app/src/main/assets
        wget -q "https://github.com/unarto/Xraycorev26.1.3/releases/download/V1.0.0/libv2ray.aar" -O app/libs/libv2ray.aar || true

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build APK Split via Gradle
      run: ./gradlew assembleDebug

    - name: Upload Artifact ARM64 (v8a)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-arm64-v8a
        path: |
          app/build/outputs/apk/debug/*arm64-v8a*.apk
          app/build/outputs/apk/debug/**/*arm64-v8a*.apk

    - name: Upload Artifact ARMV7A (v7a)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-armeabi-v7a
        path: |
          app/build/outputs/apk/debug/*armeabi-v7a*.apk
          app/build/outputs/apk/debug/**/*armeabi-v7a*.apk
